apiVersion: v1
kind: page
spec:
  id: Z6-XAOt
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Tabs
          name: tabs
          layout:
            horizontalAlign: center
    - component: PageRow
      name: pageRow1
      children:
        - component: DataGrid
          name: dataGrid
    - component: PageRow
      name: pageRow4
      children:
        - component: Tabs
          name: tabs1
    - component: PageRow
      name: pageRow2
      children:
        - component: DataGrid
          name: dataGrid1
    - component: PageRow
      name: pageRow3
      children:
        - component: DataGrid
          name: dataGrid2
